server:
  port: 8000

spring:
  application:
    name: forex-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./forex-service/db/${forex-h2-db}
    username: ${forex-h2-user}
    password: ${forex-h2-pass}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}