spring:
  application:
    name: currency-gateway

  cloud:
    gateway:
      routes:
        - id: forex-service
          uri: http://localhost:8000/
          predicates:
            - Path=/forex/**
          filters:
            - StripPrefix=1

        - id: currency-conversion-service
          uri: http://localhost:8100/
          predicates:
            - Path=/conversion/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
