spring:
  application:
    name: currency-gateway

  cloud:
    gateway:
      routes:
        - id: forex-service
          uri: ${FOREX_URL:http://localhost:8000/}
          predicates:
            - Path=/forex/**
          filters:
            - StripPrefix=1

        - id: currency-conversion-service
          uri: ${CURRENCY_CONVERSION_URL:http://localhost:8100/}
          predicates:
            - Path=/conversion/**
          filters:
            - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}