server:
  port: 8100

spring:
  application:
    name: currency-conversion-service
  cloud:
    openfeign:
      client:
        config:
          postClient:
            url: ${FEIGN_URL:http://localhost:8000/}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
